[package]
name = "valgrindparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = {version = "1.10.*"}
lazy_static = {version = "1.4.*"}
globset = {version = "0.4.*"}